# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

strategy:
  matrix:
    windows:
      imageName: STDT-RUSSAL7

pool: Self Host

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: PowerShell@2
  inputs:
    filePath: '.\msfsskim.ps1'
    arguments: '$(FolderToSkim) $(Build.ArtifactStagingDirectory)'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactsStagingDirectory)'
    artifact: 'MSFS Content Security Review Results'
    publishLocation: 'pipeline'

